name: Create version
description: tag and create new version in github
author: Kamontat Chantrachirathumrong

runs:
  using: "composite"
  steps:
    - name: Setup golang
      uses: actions/setup-go@v4
      with:
        go-version: "1.20"
    - name: Install git-chglog
      shell: bash
      run: |
        go install github.com/git-chglog/git-chglog/cmd/git-chglog@latest
    - name: git-chglog version
      shell: bash
      run: |
        git-chglog --version
    - name: create new version
      run: $GITHUB_ACTION_PATH/create-version.sh
      shell: bash
