name: Set up asdf
description: Set up asdf and install tools based on .tool-versions file
author: Kamontat Chantrachirathumrong

inputs:
  ref:
    description: asdf reference to install
    default: master
  workdir:
    description: all commands will run from this directory
    default: ${{ github.workspace }}
  tool-install:
    description: install tool based from .tool-versions file
    default: "false"

runs:
  using: node20
  pre: pre.js
  main: index.js
  post: post.js
