name: Notification
description: send notify to Slack
author: Kamontat Chantrachirathumrong

runs:
  using: "composite"
  steps:
    - name: Send message to slack
      run: $GITHUB_ACTION_PATH/notification.sh
      shell: bash
      env:
        GIT_REPO: ${{ github.repository }}
        GIT_REF: ${{ github.ref_name }}
        GIT_AUTHOR: ${{ github.actor }}
        GIT_COMMIT: ${{ github.sha }}
        GITHUB_ACTION_ID: ${{ github.run_id }}
