name: Create version
description: Create Github release and add tags
author: Kamontat Chantrachirathumrong

runs:
  using: "composite"
  steps:
    - name: Create version
      shell: bash
      run: $GITHUB_ACTION_PATH/create-version.sh
      env:
        GITHUB_DEFAULT_TOKEN: ${{ github.token }}
