name: Release information
description: get release information
author: Kamontat Chantrachirathumrong

outputs:
  environment:
    description: Environment name
    value: ${{ steps.default.outputs.environment }}
  app-name:
    description: Application name
    value: ${{ steps.default.outputs.app-name }}
  app-path:
    description: Application path
    value: ${{ steps.default.outputs.app-path }}
  version:
    description: Application version
    value: ${{ steps.default.outputs.version }}
  git-tag:
    description: Git tag name
    value: ${{ steps.default.outputs.git-tag }}
  mode:
    description: Release mode
    value: ${{ steps.default.outputs.mode }}
  docker-image:
    description: Docker image name
    value: ${{ steps.default.outputs.docker-image }}
  docker-context:
    description: Docker context path
    value: ${{ steps.default.outputs.docker-context }}
  docker-file:
    description: Dockerfile path
    value: ${{ steps.default.outputs.docker-file }}

runs:
  using: "composite"
  steps:
    - id: default
      name: Get information
      run: $GITHUB_ACTION_PATH/get-info.sh
      shell: bash
