name: Create version
description: tag and create new version in github
author: Kamontat Chantrachirathumrong

runs:
  using: "composite"
  steps:
    - name: create new version
      run: $GITHUB_ACTION_PATH/create-version.sh
      shell: bash
      env:
        GITHUB_DEFAULT_TOKEN: ${{ github.token }}
