name: Typescript Example
description: Example actions written on Typescript
author: Kamontat Chantrachirathumrong

inputs:
  name:
    description: example name

# outputs:
#   output:
#     description: Output description

runs:
  using: node20
  pre: pre.js
  main: index.js
  post: post.js
