name: Main

on:
  push:

jobs:
  example-workflow:
    uses: cognius/github-actions/.github/workflows/example.yaml@v2
  actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          package_json_file: .actions/package.json
      - name: Set up nodejs
        uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version-file: .actions/package.json
          cache-dependency-path: .actions/pnpm-lock.yaml
      - name: Install actions dependencies
        working-directory: .actions
        run: pnpm install
      - name: Lint actions
        working-directory: .actions
        run: pnpm lint
      - name: Test actions
        working-directory: .actions
        run: pnpm test
      - name: Build actions
        working-directory: .actions
        run: pnpm build
  example-action:
    runs-on: ubuntu-latest
    needs:
      - actions
    steps:
      - uses: cognius/github-actions/example-ts@v2
  setup-asdf-action:
    runs-on: ubuntu-latest
    needs:
      - actions
    steps:
      - uses: actions/checkout@v3
      - uses: cognius/github-actions/setup-asdf@v2
        with:
          tool-install: true
          workdir: "${{ github.workspace }}/.tests/asdf"
      - run: asdf --version
      - run: k6 version
        working-directory: "${{ github.workspace }}/.tests/asdf"
      - run: helm version
        working-directory: "${{ github.workspace }}/.tests/asdf"
  create-hosts-action:
    runs-on: ubuntu-latest
    needs:
      - actions
    steps:
      - uses: cognius/github-actions/create-hosts@v2
        with:
          hosts: example.com,hello-world.com
      - run: docker run --name nginx --rm --publish 9999:80 --detach nginx:stable
      - run: curl -I "example.com:9999"
      - run: curl -I "hello-world.com:9999"
      - run: docker stop nginx
